<!DOCTYPE html>
<html>
<head>
    <title>Exercício 6.2</title>

    <script>

        try {
        
        // Código que pode gerar uma exceção
        const resultado = 10 / 0; // Isso causará uma exceção de divisão por zero
        console.log("Isso será impresso se não ocorrerem exceções.");

        } catch (erro) {
        // Captura e lida com a exceção

        console.error("Ocorreu uma exceção: " + erro.message);
        } finally {
        // O bloco finally é opcional e sempre é executado, independentemente de exceções
        
        console.log("Este bloco é sempre executado, mesmo que uma exceção tenha ocorrido.");
        }

        console.log("O programa continua aqui após o tratamento da exceção.");


    </script>

</head>
<body>
    
</body>
</html>